version: '3'
services:

  postgres:
    container_name: 'postgres'
    image: 'postgres:12-alpine3.18'
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ${PGENV}
    volumes:
      - ${PGVOLUME}
      - ${PGINIT}
    networks:
      - postgres

  mongodb:
    container_name: 'mongodb'
    image: 'mongo'
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - ${MONGO_ENV}
    volumes:
      - ${MONGO_INIT}
      - ${MONGO_VOLUME}
      - ${MONGO_LOG}
    networks:
      - mongo

  mongo-express:
    container_name: 'mongo-express'
    image: 'mongo-express:1.0.0-20-alpine3.18'
    restart: always
    ports:
      - '27018:8081'
    env_file:
      - ${ME_ENV}
    networks:
      - mongo
    depends_on:
      - mongodb

networks:
  postgres:
    driver: bridge
  mongo:
    driver: bridge
