server:
  port: 8083
spring:
  application:
    name: report
  datasource:
    url: jdbc:postgresql://localhost:5432/point_transaction
    username: developer
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true